name: Build/test suite

on:
  push:
    branches:
      mainline
  pull_request:
    branches:
      mainline

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
          - os: macos-latest

    name: |
      test ${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out project
        uses: actions/checkout@v2

      - name: Install Linux dependencies
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo apt install libmpfr-dev

      - name: Install MacOS dependencies
        if: startsWith(matrix.os, 'macos')
        run: |
          brew install mpfr catch2

      - name: CMake configure and build
        uses: threeal/cmake-action@v1.3.0
        with:
          options: BUILD_TESTING=ON
          run-build: true

      - name: Run tests
        run: |
          build/test/tests
